{% set name = "rouge" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rouge-{{ version }}.tar.gz
  sha256: 12b48346ca47d6bcf3c45061f315452b9ccec0620ee895ec85b7efc3d54aae34

build:
  entry_points:
    - rouge=bin.rouge_cmd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - bin
    - rouge
  commands:
    - pip check
    - rouge --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/pltrdy/rouge
  summary: Full Python ROUGE Score Implementation (not a wrapper)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
